# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: nginx-dev
#   namespace: default
#   labels:
#     k8s-app: dev-env1
# spec:
#   selector:
#     matchLabels:
#       name: nginx-dev
#   template:
#     metadata:
#       labels:
#         name: nginx-dev
#     spec:
#       nodeSelector:
#         dde.role: DevVM
#       containers:
#         - name: ngin-dev
#           image: docker.io/library/nginx:latest
#           ports:
#           - name: react-dev
#             containerPort: 80
#             hostPort: 8080
#           volumeMounts:
#             - mountPath: /etc/nginx/nginx.conf
#               name: nginx-config

#       volumes:
#         - name: static
#           hostPath:
#               path: /tmp/www
#               type: Directory
#         - name: nginx-config
#           hostPath:
#               path: /tmp/nginx/nginx.conf
#               type: Directory
#         - name: node-modules
#           emptyDir: {}
              
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: react-dev
  namespace: default
  labels:
    k8s-app: dev-env1
spec:
  selector:
    matchLabels:
      name: react-dev
  template:
    metadata:
      labels:
        name: react-dev
    spec:
      nodeSelector:
        dde.role: DevVM
      containers:
        - name: react-dev
          image: docker.io/pogorelov/demo-react-app:dev
          ports:
          - name: react-dev
            containerPort: 3000
            hostPort: 3000
          volumeMounts:
            - mountPath: /app
              name: react-app
            - mountPath: /app/node_modules
              name: node-modules
      volumes:
        - name: react-app
          hostPath:
              path: /home/vagrant/react-app
              type: Directory
        - name: node-modules
          emptyDir: {}
              