
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flask-dev
  namespace: default
  labels:
    k8s-app: dev-env1
spec:
  selector:
    matchLabels:
      name: flask-dev
  template:
    metadata:
      labels:
        name: flask-dev
    spec:
      nodeSelector:
        # dde.role: devEnv-front
        dde.role: DevVM
      containers:
        - name: flask-dev
          image: docker.io/pogorelov/demo-flask-app:dev
          imagePullPolicy: Always
          ports:
          - name: flask-dev
            containerPort: 5000
            hostPort: 5000
          volumeMounts:
            - mountPath: /usr/src/app
              name: flask-app
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_DEBUG
              value: "1"
            - name: MINIO_ACCES_KEY
              value: "kn5jW21ElV63Kk497f28"
            - name: MINIO_SECRET_KEY
              value: "fPL+scGH/e57L558R/sYxj/1Ao7P8+DSKIR6Nez6"
            - name: MINIO_URL
              value: "minio.default.svc.cluster.local"
      volumes:
        - name: flask-app
          hostPath:
              # path: /mnt/c/projects/DevOpsFestDemo/flask-app
              path: /home/vagrant/DevOpsFestDemo/flask-app
              type: Directory

